  services:
    mysql:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "cloudchaser"
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql  # Updated to match defined volume name
      networks:
        - app_network

    sonarqube:
      image: sonarqube:8.9.7-community
      restart: unless-stopped
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
      ports:
        - "9000:9000"
        - "9092:9092"
      networks:
        - app_network
      depends_on:
        - mysql

    nexus:
      image: sonatype/nexus3
      volumes:
        - nexus_data:/nexus-data
      ports:
        - "8081:8081"
      networks:
        - app_network

  networks:
    app_network:
      driver: bridge
      external: true

  volumes:
    mysql_data:            # Defined mysql_data volume
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    nexus_data:
