services:
  spring_app:
    image: ghassenmassaoud/ghassenmassaoud_5arctic3_g2_unihub:latest
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloudchaser
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # Make sure to set this or leave it empty as needed
    ports:
      - "8083:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    external: true
