version: "3.8"

services:
  mysql_db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "cloudchaser"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql_db
    restart: on-failure
    ports:
      - "8090:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:3306/cloudchaser?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.servlet.context-path": "/api",
        "server.port": "8081"
      }'
    volumes:
      - .m2:/root/.m2
      - .:/workdir/server/src
      - ./src/main/resources/application.yml:/workdir/server/src/main/resources/application.yml
    stdin_open: true
    tty: true
  bee-ui:
    container_name: smartcloud
    image: smart
    ports:
      - 80:80

    depends_on:
      - app

volumes:
  db:







